# Generated by Django 4.0.6 on 2022-07-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_task', '0002_alter_sub_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_task',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
